### ISSUE TITLE
setChecked() doesn't work

### ISSUE THREAD

**Issue by emreaydogdu** [bitvale/Switcher#4]

**Comment by bitvale** [comment]
Can you provide usage example?

**Comment by emreaydogdu** [comment]
```
<com.bitvale.pacbutton.SwitcherX
    android:id="@+id/switcher"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:switcher_on_color="@color/on"
    app:switcher_off_color="@color/off"
    app:switcher_icon_color="@color/icon" />
```
```
SwitcherX switcher;
switcher = findViewByid(R.id.switcher);
switcher.setChecked(false);
```
> will always show checked

**Comment by emreaydogdu** [comment]
@bitvale 

```
<com.bitvale.pacbutton.SwitcherX
    android:id="@+id/switcher"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:switcher_on_color="@color/on"
    app:switcher_off_color="@color/off"
    app:switcher_icon_color="@color/icon" />
```
```
SwitcherX switcher;
switcher = findViewByid(R.id.switcher);
switcher.setChecked(false);
```
> will always show checked true

**Comment by bitvale** [comment]
Thank you for submitting! I found an error in project description page.

Try com.bitvale.**switcher**.SwitcherX  instead of com.bitvale.**pacbutton**.SwitcherX

**Comment by emreaydogdu** [comment]
@bitvale 
-------
That's not the problem. I already use 
`
<com.bitvale.switcher.SwitcherX>
` 
> setChecked() doesn't change the state. 
> also if I set 
`checked="false" `
> İt shows reverse disabled and if I pressed there ist a buggy animation from switching false to true

`Example` https://i.imgur.com/a/KFNpcuH

**Comment by bitvale** [comment]
Fixed in version 1.0.1 Thank You!

**Comment by emreaydogdu** [comment]
Thank you. The States are right now but the animation is still wrong and same like example before. İf I use 
> setChecked(false, true  )(Withanimation) **wrong**      
> setChecked (false,false) **everything is fine**

**Comment by bitvale** [comment]
Now I can not catch this.

Please try this: open `MainActivity ` in demo app and replace `setOncheckedChangeListener(s)`

```
switcher_x.setOnCheckedChangeListener { checked ->
            switcher_c.setChecked(checked) // add this line
            if (checked) tv_switcher_x.setTextColor(defaultColor)
            else tv_switcher_x.setTextColor(disabledColor)
        }

        switcher_c.setOnCheckedChangeListener { checked ->
            switcher_x.setChecked(checked) // add this line
            if (checked) tv_switcher_c.setTextColor(defaultColor)
            else tv_switcher_c.setTextColor(disabledColor)
        }
```

Let me know if it doesn't work .For me it works as expected.

**Comment by bitvale** [comment]
Now I can not catch this.

Please try this: open `MainActivity ` in demo app and replace `setOncheckedChangeListener(s)`

```
switcher_x.setOnCheckedChangeListener { checked ->
            switcher_c.setChecked(checked) // add this line
            if (checked) tv_switcher_x.setTextColor(defaultColor)
            else tv_switcher_x.setTextColor(disabledColor)
        }

switcher_c.setOnCheckedChangeListener { checked ->
            switcher_x.setChecked(checked) // add this line
            if (checked) tv_switcher_c.setTextColor(defaultColor)
            else tv_switcher_c.setTextColor(disabledColor)
        }
```

Let me know if it doesn't work. For me it works as expected.
